version: '3.8'

services:
  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "80:80"
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
