version: '3.8'

services: # network of services
  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - chatapp
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - chatapp

networks:
  chatapp:

